### ISSUE TITLE
Pangolin-data 1.6 pre-release not in sync with assignment-cache version (will not run) - version 4.0.5

### ISSUE THREAD

**Issue by jacaravas** [cov-lineages/pangolin-data#6]
Note: I resolved this problem by manually installing the 1.3 tagged version of pangolin-data, so I do not require a fix.  This is to document possibly unexpected or undesired behavior 

I created a new conda environment and pangolin installation this morning using the developer option (environment.yml, pip install) to install the tagged v4.0.5 version of pangolin and then running the --add-assignment-cache option.

When I run pangolin --update-data, I get
```
Latest for pangolin-data is v1.3
pangolin-data (1.6) is newer than latest stable release (v1.3), not updating.
Latest for constellations is v0.1.7
constellations already latest release (v0.1.7)
Latest for pangolin-assignment is v1.3
pangolin-assignment already latest release (v1.3)
```
And when I tried to run pangolin, I got the message:
```
Error: pangolin_assignment cache version v1.3 does not match pangolin_data version 1.6. Run "pangolin --update-data" to fetch latest versions of both.
```

I realize this is not a standard installation process (downgraded pangolin version and installed through pip rather than the conda-forge), so the issue may be highly specific to my situation.  I wanted to point it out in case downloading pre-release pangolin-data  is not expected behavior when using a tagged version or if having it reported as out of sync with the assignment cache is an error. 

For anyone else who happens to find themselves in a similar situation, the solution is:
```
conda activate pangolin
git clone https://github.com/cov-lineages/pangolin-data.git
cd pangolin-data
git checkout tags/v1.3
pip install .
```

**Comment by aineniamh** [comment]
Hi @jacaravas, when you run `pangolin --update-data` it doesn't update to pre-release tags. It seems that the conda installation did as it pip installs from the main branch. I think the installation you did was timed slightly unfortunately as there's usually only a few hours between the full release and the pre-release (we do the pre-releases for GISAID's benefit). 

This specific issue should be resolved now but I'm not sure how to get the developer install option to update only full releases through the conda environment.

**Comment by donutbrew** [comment]
Just a quick followup, but is the intention to have `pangolin-data` versions represent a distinct and unchanging set of component versions (i,e. Usher, assignment cache, designations, etc)?

**Comment by aineniamh** [comment]
pangolin-data will have all the lineage-related data files that pangolin needs to run (we no longer need pangoLEARN). 
It currently contains the lineage alias file, the designation cache, the pangoLEARN model files and the usher tree protobuf file- this simplifies the versioning because all these data correspond to a particular pango-designation version number. 
If additional methods get incorporated the necessary data files for a given pango-designation version will also exist here. 

The assignment cache does not get included here as it's merely a speedup for the usher method and is a pretty large file, which most users won't need.

**Comment by donutbrew** [comment]
OK, so we should make sure that if we are using the assignment cache, it is the same version as the pangolin-data release's usher version?

**Comment by aineniamh** [comment]
I don't think it'll let you do otherwise, like the error you got above!

**Comment by AngieHinrichs** [comment]
There was a window of many hours yesterday when pangolin-data had a v1.6 pre-release (and v1.6 contents in the main branch) but pangolin-assignment did not and was still at v1.3 in the main branch (the v1.6 data was still in a prerelease branch).  The smaller we can make that window when pangolin-data and pangolin-assignment main branches have different versions, the better for new installations that fetch the main branch not latest release as Áine said.  

Sorry about the inconvenience @jacaravas and thanks for posting the pip install workaround.  I will look into whether there's a way to specify "latest full release" (instead of latest main or a specific version) for the pip github URLs in environment.yml, but in the meantime, hopefully @aineniamh and I can synchronize our updates of pangolin-data and pangolin-assignment main branches better to shrink the window of badness for new installs.  :)

(And if you haven't already, running `pangolin --update-data` or making a new dev installation today should work fine and get you the new v1.6 release!)

**Comment by jacaravas** [comment]
Thank you for your help, @aineniamh and @AngieHinrichs.  I don't expect this to be an ongoing issue for me.  This was a special case where I needed to synchronize installations on different machines and upgrading the older installation wasn't an option.  I picked a bad time to do weird stuff.

Thanks again!
